export const Users = [
  {
    id: 1,
    profilePicture: "Assets/person1.webp",
    username: "ibrahim takla",
  },
  {
    id: 2,
    profilePicture: "Assets/person2.jpeg",
    username: "Anus",
  },
  {
    id: 3,
    profilePicture: "Assets/person3.jpeg",
    username: "Alvi",
  },
  {
    id: 4,
    profilePicture: "Assets/person4.jpeg",
    username: "Ali",
  },
  {
    id: 5,
    profilePicture: "Assets/person5.jpeg",
    username: "Hina",
  },
  {
    id: 6,
    profilePicture: "Assets/person6.jpeg",
    username: "Bakri",
  },
  {
    id: 7,
    profilePicture: "Assets/person7.jpeg",
    username: "Ramsha",
  },
  {
    id: 8,
    profilePicture: "Assets/person8.jpeg",
    username: "Aliza",
  },
  {
    id: 9,
    profilePicture: "Assets/person9.jpeg",
    username: "Hasham",
  },
  {
    id: 10,
    profilePicture: "Assets/person10.jpeg",
    username: "Saab",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Caption",
    photo: "Assets/post1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "Assets/post2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Caption",
    photo: "Assets/post3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "Assets/post4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "Assets/post5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "Assets/post6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Caption",
    photo: "Assets/post7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "Assets/post8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Caption",
    photo: "Assets/post9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "Assets/post10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
